# Form implementation generated from reading ui file 'addCon.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 240)
        MainWindow.setMinimumSize(QtCore.QSize(320, 240))
        MainWindow.setMaximumSize(QtCore.QSize(320, 240))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.editFirst = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.editFirst.setGeometry(QtCore.QRect(100, 30, 113, 20))
        self.editFirst.setObjectName("editFirst")
        self.editLast = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.editLast.setGeometry(QtCore.QRect(100, 60, 113, 20))
        self.editLast.setObjectName("editLast")
        self.editPhone = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.editPhone.setGeometry(QtCore.QRect(100, 90, 113, 20))
        self.editPhone.setObjectName("editPhone")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 61, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 61, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 71, 20))
        self.label_3.setObjectName("label_3")
        self.Enter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Enter.setGeometry(QtCore.QRect(130, 140, 56, 17))
        self.Enter.setObjectName("Enter")
        self.errorFirst = QtWidgets.QLabel(parent=self.centralwidget)
        self.errorFirst.setGeometry(QtCore.QRect(220, 30, 91, 21))
        self.errorFirst.setText("")
        self.errorFirst.setObjectName("errorFirst")
        self.errorLast = QtWidgets.QLabel(parent=self.centralwidget)
        self.errorLast.setGeometry(QtCore.QRect(220, 60, 91, 21))
        self.errorLast.setText("")
        self.errorLast.setObjectName("errorLast")
        self.errorPhone = QtWidgets.QLabel(parent=self.centralwidget)
        self.errorPhone.setGeometry(QtCore.QRect(220, 90, 91, 21))
        self.errorPhone.setText("")
        self.errorPhone.setObjectName("errorPhone")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Contact Book"))
        self.label.setText(_translate("MainWindow", "First Name:"))
        self.label_2.setText(_translate("MainWindow", "Last Name:"))
        self.label_3.setText(_translate("MainWindow", "Phone Number:"))
        self.Enter.setText(_translate("MainWindow", "ENTER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
