# Form implementation generated from reading ui file 'addview.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 350)
        MainWindow.setMinimumSize(QtCore.QSize(500, 350))
        MainWindow.setMaximumSize(QtCore.QSize(500, 350))

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.addButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(175, 120, 180, 25))
        self.addButton.setObjectName("addButton")

        self.remButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.remButton.setGeometry(QtCore.QRect(175, 160, 180, 25))
        self.remButton.setObjectName("remButton")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Contact Book"))
        self.addButton.setText(_translate("MainWindow", "Add Contact"))
        self.remButton.setText(_translate("MainWindow", "View Contacts"))
