# Form implementation generated from reading ui file 'contacts.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 520)
        MainWindow.setMinimumSize(QtCore.QSize(750, 520))
        MainWindow.setMaximumSize(QtCore.QSize(750, 520))

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.ContactList = QtWidgets.QListWidget(parent=self.centralwidget)
        self.ContactList.setGeometry(QtCore.QRect(20, 40, 370, 360))
        self.ContactList.setObjectName("ContactList")

        self.ConInfo = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.ConInfo.setGeometry(QtCore.QRect(420, 40, 300, 220))
        self.ConInfo.setObjectName("ConInfo")

        self.Edit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Edit.setGeometry(QtCore.QRect(420, 310, 130, 35))
        self.Edit.setObjectName("Edit")

        self.Menu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Menu.setGeometry(QtCore.QRect(590, 310, 130, 35))
        self.Menu.setObjectName("Menu")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Contact Book"))
        self.Menu.setText(_translate("MainWindow", "MAIN MENU"))
        self.Edit.setText(_translate("MainWindow", "EDIT CONTACT"))
