# Form implementation generated from reading ui file 'IDReg.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 350)
        MainWindow.setMinimumSize(QtCore.QSize(500, 350))
        MainWindow.setMaximumSize(QtCore.QSize(500, 350))

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 40, 180, 30))
        self.label.setObjectName("label")

        self.IDLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.IDLine.setGeometry(QtCore.QRect(180, 100, 180, 25))
        self.IDLine.setObjectName("IDLine")

        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 120, 25))
        self.label_2.setObjectName("label_2")

        self.EnterButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.EnterButton.setGeometry(QtCore.QRect(210, 170, 80, 30))
        self.EnterButton.setObjectName("EnterButton")

        self.label_error = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_error.setGeometry(QtCore.QRect(180, 135, 200, 25))
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Contact Book"))
        self.label.setText(_translate("MainWindow", "CONTACT BOOK"))
        self.label_2.setText(_translate("MainWindow", "ID (8 DIGITS):"))
        self.EnterButton.setText(_translate("MainWindow", "ENTER"))
